# CLEANED application.yml - Remove ALL CORS and Gateway route configs from here

spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:http://config-server:8888"
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: false
      retry:
        initial-interval: 2000
        max-attempts: 6
      enabled: true

# NO GATEWAY ROUTES HERE - They're in gateway.yml only!
# NO CORS CONFIG HERE - It's in gateway.yml only!

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: false
    fetch-registry: true


management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example: DEBUG