spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:http://config-server:8888"  # FIXED: Added missing closing quote
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: false
      retry:
        initial-interval: 2000
        max-attempts: 6

# JWT Configuration
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 hours in milliseconds

# Server Configuration
server:
  port: 8090

# Add Eureka registration
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true

# Add management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Logging for debugging
logging:
  level:
    com.example.auth_service: DEBUG
    org.springframework.security: DEBUG