server:
  port: 8761

eureka:
  instance:
    hostname: discovery-service
  client:
    register-with-eureka: false
    fetch-registry: false
    
spring:
  application:
    name: discovery
  cloud:
    config:
      enabled: false